export enum TrackingEventType {
  CREATED = 'CREATED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  ARRIVED_HUB = 'ARRIVED_HUB',
  DEPARTED_HUB = 'DEPARTED_HUB',
  DELAYED = 'DELAYED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
