import { TypeUser } from './TypeUser';

export interface UserSchema {
  id?: number; // Optional, as it might be generated by the backend
  name: string;
  lastName: string;
  type: TypeUser;
  creationDate?: string; // Optional, as it might be generated by the backend
  updatedDate?: string; // Optional, as it might be generated by the backend
}
